### ISSUE TITLE
指定特定的控制器輸出跨網域標頭

### ISSUE THREAD

**Issue by liaosankai** [pronebel/think-cors#1]
您好，從文件上來看，在設置後所有控制器都會輸出跨網域標題(headers)，請問如果只是要指定幾個特定的控制器可以跨網域，而不是全部控制器，應該如何設置？

**Comment by pronebel** [comment]
当前增加了exclude判断，exclude的数组配置项，如果请求的url值，通过exclude判断为true，则跳过cors的设置。
这里跟您需要的有点反向了。
但通过里面的正则反过来写，是能够满足您的情况的。

ps:
抱歉，这么久才给你回复。希望和您一样有技术的激情。
