### ISSUE TITLE
新增关于websocket的设置

### ISSUE THREAD

**Issue by xb594328980** [pronebel/think-cors#4]
是否可以增加过滤websocket的设置 ，指当访问请求为websocket时则直接return 而不去处理

**Comment by pronebel** [comment]
目前,已支持跳过特定的url,具体配置请见文档  exclude配置:  ,https://github.com/pronebel/think-cors/blob/master/docs/README.CN.md#exclude-配置

你说的这个思路,我后面研究下,socket请求在http中是否有特殊标记,假设如果有特殊标记,是可以根据特殊标记进行return处理的.

如需要,可以加我QQ

**Comment by xb594328980** [comment]
在http中存在socket这个属性，但是在request_begin这个过程中还未创建 所以我之前说的那个思路估计行不通 后面在更新了1.1.2版本之后就通过过滤地址 实现的socket的功能
