### ISSUE TITLE
添加后会与websocket冲突，导致websocket通信失败

### ISSUE THREAD

**Issue by mrz9** [pronebel/think-cors#6]
加入websocket后，目前使用socket.io版本，放心如果开启了think-cors就会导致websocket通信不成功，把hook.js里面的request_begin:['cors']干掉后，websocket才能正常通信

**Comment by pronebel** [comment]
请参考这个解决,  https://github.com/pronebel/think-cors/issues/4

最新的版本里支持跳过某些规则的URL
