### ISSUE TITLE
配置后跨域上传图片无效，调用接口数据正常

### ISSUE THREAD

**Issue by shihuojian** [pronebel/think-cors#7]
最近测试，发现配置好后跨域上传图片无效，调用接口数据却是是正常的。也可能是我配置哪里错了

**Comment by pronebel** [comment]
在think-cors/example/thinkjs/test/index.html 中配置了上传图片文件的示例,测试是ok的, 
hook里面配置 cors则可以发送请求,接口可以拿到file的数据,  不配置cors则 提示 跨域
